// import type {Metadata} from "next";
import "./globals.css";
import {Footer, Header, Sidebar, Up} from "@/components";
import styles from './page.module.css';
import {getMenu} from "@/api/menu";
import {AppContextProvider} from "@/context/app.context";
// import Script from "next/script";

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {

    const firstCategory = 0;
    const menu = await getMenu(firstCategory);

    return (
        <html lang="ru">
        {/*ЭТО СКРИПТ ДЛЯ ЯНДЕКС МЕТРИКИ ИЛИ КАКОГО ИСПОЛНЯЕМОГ ФАЙЛА*/}
        {/*<head>*/}
        {/*    <Script src='' strategy='worker'/>*/}
        {/*<head/>*/}

        <body>
        <AppContextProvider menu={menu} firstCategory={firstCategory}>
            <div className={styles.wrapper}>
                <Header menu={menu} firstCategory={firstCategory} className={styles.header}/>
                <Sidebar menu={menu} firstCategory={firstCategory} className={styles.sidebar}/>
                <div className={styles.body}>
                    {children}
                </div>
                <Footer className={styles.footer}/>
                <Up/>
            </div>
        </AppContextProvider>
        </body>
        </html>
    );
}
